#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["tiktoken"]
# ///
"""Compute Whisper's `non_speech_tokens` set for the English-only build.

Whisper's greedy decoder suppresses a fixed set of token IDs that correspond to
symbols (punctuation past the basics, musical notes, brackets, etc.) at every
step — see `mlx_whisper/tokenizer.py`'s `non_speech_tokens` property. The set is
deterministic per vocab, so we compute it once here and bake the result into
`Transcription/WhisperDecoding.swift` as a literal `Set<Int>` rather than
porting tiktoken's encoder to Swift just to recompute a constant.

Run from the repo root after fetching gpt2.tiktoken:

    scripts/compute-non-speech-tokens.py

The script prints a Swift literal you can paste under the `nonSpeechTokens`
declaration. Re-run if `gpt2.tiktoken` ever changes (it shouldn't — the vocab
is frozen upstream).
"""

from __future__ import annotations

import base64
from pathlib import Path

import tiktoken


VOCAB_PATH = Path("Relay Notes/Relay Notes/Resources/whisper-tiny.en/gpt2.tiktoken")


def load_ranks(path: Path) -> dict[bytes, int]:
    ranks: dict[bytes, int] = {}
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        token, rank = line.split()
        ranks[base64.b64decode(token)] = int(rank)
    return ranks


def build_encoding(ranks: dict[bytes, int]) -> tiktoken.Encoding:
    """Recreate the English-only Whisper encoding."""
    # Mirror tokenizer.py's append order: eot, sot, 99 language slots,
    # translate, transcribe, startoflm, startofprev, nospeech, notimestamps.
    specials = ["<|endoftext|>", "<|startoftranscript|>"]
    specials += [f"<|lang_{i}|>" for i in range(99)]
    specials += [
        "<|translate|>", "<|transcribe|>", "<|startoflm|>",
        "<|startofprev|>", "<|nospeech|>", "<|notimestamps|>",
    ]
    n_vocab = len(ranks)
    special_tokens = {tok: n_vocab + i for i, tok in enumerate(specials)}
    return tiktoken.Encoding(
        name="whisper-en",
        explicit_n_vocab=n_vocab + len(specials),
        pat_str=(
            r"""'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| """
            r"""?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+"""
        ),
        mergeable_ranks=ranks,
        special_tokens=special_tokens,
    )


def non_speech_tokens(encoding: tiktoken.Encoding) -> list[int]:
    """Direct port of `Tokenizer.non_speech_tokens` from mlx_whisper/tokenizer.py."""
    symbols = list("\"#()*+/:;<=>@[\\]^_`{|}~「」『』")
    symbols += "<< >> <<< >>> -- --- -( -[ (' (\" (( )) ((( ))) [[ ]] {{ }} ♪♪ ♪♪♪".split()
    miscellaneous = set("♩♪♫♬♭♮♯")

    result: set[int] = {encoding.encode(" -")[0], encoding.encode(" '")[0]}
    for symbol in symbols + list(miscellaneous):
        for tokens in (encoding.encode(symbol), encoding.encode(" " + symbol)):
            if len(tokens) == 1 or symbol in miscellaneous:
                result.add(tokens[0])
    return sorted(result)


def main() -> None:
    ranks = load_ranks(VOCAB_PATH)
    encoding = build_encoding(ranks)
    ids = non_speech_tokens(encoding)

    print(f"// {len(ids)} non-speech token IDs (from gpt2.tiktoken, English-only build).")
    print(f"// Generated by scripts/compute-non-speech-tokens.py — re-run if gpt2.tiktoken changes.")
    print(f"static let nonSpeechTokens: Set<Int> = [")
    for i in range(0, len(ids), 10):
        chunk = ids[i:i + 10]
        print("    " + ", ".join(str(x) for x in chunk) + ",")
    print(f"]")


if __name__ == "__main__":
    main()
